namespace Zega
{
    public partial class Z80
    {
        // TODO - see if we can make this private again. I don't like how it's public just so classes outside of Z80.cs,
        // namely the unit tests, can set and get them freely for initial setup and post-result Asserts

        // TODO add halted bool
        // TODO add IFF1 and IFF2
        // TODO add interrupt mode enum

        // TODO - instead of creating new List<int>s in instruction group setup, create a single instance of each list we need
        // e.g. we used new List<int> { 4, 3 } a lot. So just create one 4,3 instance and re-use

        // TODO - should I refactor all instruction method names to be longer but more descriptive?
        // e.g. RLCA -> RotateLeftCarryA

        public readonly Registers Registers;
        private readonly IMemory _memory;

        private readonly IList<IInstructionGroup> _prefixedInstructionGroups;
        private readonly IInstructionGroup _nonPrefixedInstructionGroup;

        public Z80(IMemory memory, Registers? registers = null)
        {
            _memory = memory ?? throw new ArgumentNullException(nameof(memory));
            Registers = registers ?? new Registers();

            // TODO - after implementing all opcodes, if it turns out to be true that mCycles always equals tCycles.Length, then remove
            // the mCycles param and just return tCycles.Length when you need it

            _prefixedInstructionGroups = new List<IInstructionGroup>
            {
                new CBInstructionGroup(new Dictionary<byte, Instruction>
                {
                    { 0x40, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x41, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x42, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x43, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x44, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x45, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x46, new Instruction(BitBHL, new List<int> { 4, 4, 4 }) },
                    { 0x47, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x48, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x49, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x4A, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x4B, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x4C, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x4D, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x4E, new Instruction(BitBHL, new List<int> { 4, 4, 4 }) },
                    { 0x4F, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x50, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x51, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x52, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x53, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x54, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x55, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x56, new Instruction(BitBHL, new List<int> { 4, 4, 4 }) },
                    { 0x57, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x58, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x59, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x5A, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x5B, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x5C, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x5D, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x5E, new Instruction(BitBHL, new List<int> { 4, 4, 4 }) },
                    { 0x5F, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x60, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x61, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x62, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x63, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x64, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x65, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x66, new Instruction(BitBHL, new List<int> { 4, 4, 4 }) },
                    { 0x67, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x68, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x69, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x6A, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x6B, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x6C, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x6D, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x6E, new Instruction(BitBHL, new List<int> { 4, 4, 4 }) },
                    { 0x6F, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x70, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x71, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x72, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x73, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x74, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x75, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x76, new Instruction(BitBHL, new List<int> { 4, 4, 4 }) },
                    { 0x77, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x78, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x79, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x7A, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x7B, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x7C, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x7D, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x7E, new Instruction(BitBHL, new List<int> { 4, 4, 4 }) },
                    { 0x7F, new Instruction(BitBR, new List<int> { 4, 4 }) },
                    { 0x80, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x81, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x82, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x83, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x84, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x85, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x86, new Instruction(ResBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0x87, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x88, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x89, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x8A, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x8B, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x8C, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x8D, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x8E, new Instruction(ResBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0x8F, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x90, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x91, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x92, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x93, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x94, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x95, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x96, new Instruction(ResBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0x97, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x98, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x99, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x9A, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x9B, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x9C, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x9D, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0x9E, new Instruction(ResBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0x9F, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xA0, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xA1, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xA2, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xA3, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xA4, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xA5, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xA6, new Instruction(ResBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0xA7, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xA8, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xA9, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xAA, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xAB, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xAC, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xAD, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xAE, new Instruction(ResBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0xAF, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xB0, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xB1, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xB2, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xB3, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xB4, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xB5, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xB6, new Instruction(ResBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0xB7, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xB8, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xB9, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xBA, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xBB, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xBC, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xBD, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xBE, new Instruction(ResBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0xBF, new Instruction(ResBR, new List<int> { 4, 4 }) },
                    { 0xC0, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xC1, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xC2, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xC3, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xC4, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xC5, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xC6, new Instruction(SetBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0xC7, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xC8, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xC9, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xCA, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xCB, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xCC, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xCD, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xCE, new Instruction(SetBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0xCF, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xD0, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xD1, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xD2, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xD3, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xD4, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xD5, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xD6, new Instruction(SetBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0xD7, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xD8, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xD9, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xDA, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xDB, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xDC, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xDD, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xDE, new Instruction(SetBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0xDF, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xE0, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xE1, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xE2, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xE3, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xE4, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xE5, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xE6, new Instruction(SetBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0xE7, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xE8, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xE9, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xEA, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xEB, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xEC, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xED, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xEE, new Instruction(SetBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0xEF, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xF0, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xF1, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xF2, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xF3, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xF4, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xF5, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xF6, new Instruction(SetBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0xF7, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xF8, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xF9, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xFA, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xFB, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xFC, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xFD, new Instruction(SetBR, new List<int> { 4, 4 }) },
                    { 0xFE, new Instruction(SetBHL, new List<int> { 4, 4, 4, 3 }) },
                    { 0xFF, new Instruction(SetBR, new List<int> { 4, 4 }) }
                }),

                new DDInstructionGroup(new Dictionary<byte, Instruction>
                {
                    { 0x36, new Instruction(LoadIXDN, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x46, new Instruction(LoadRIXD, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x4E, new Instruction(LoadRIXD, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x56, new Instruction(LoadRIXD, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x5E, new Instruction(LoadRIXD, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x66, new Instruction(LoadRIXD, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x6E, new Instruction(LoadRIXD, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x70, new Instruction(LoadIXDR, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x71, new Instruction(LoadIXDR, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x72, new Instruction(LoadIXDR, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x73, new Instruction(LoadIXDR, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x74, new Instruction(LoadIXDR, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x75, new Instruction(LoadIXDR, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x77, new Instruction(LoadIXDR, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x7E, new Instruction(LoadRIXD, new List<int> { 4, 4, 3, 5, 3 }) },
                }),
                new FDInstructionGroup(new Dictionary<byte, Instruction>
                {
                    { 0x36, new Instruction(LoadIYDN, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x46, new Instruction(LoadRIYD, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x4E, new Instruction(LoadRIYD, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x56, new Instruction(LoadRIYD, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x5E, new Instruction(LoadRIYD, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x66, new Instruction(LoadRIYD, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x6E, new Instruction(LoadRIYD, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x70, new Instruction(LoadIYDR, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x71, new Instruction(LoadIYDR, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x72, new Instruction(LoadIYDR, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x73, new Instruction(LoadIYDR, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x74, new Instruction(LoadIYDR, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x75, new Instruction(LoadIYDR, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x77, new Instruction(LoadIYDR, new List<int> { 4, 4, 3, 5, 3 }) },
                    { 0x7E, new Instruction(LoadRIYD, new List<int> { 4, 4, 3, 5, 3 }) }
                })
            };

            _nonPrefixedInstructionGroup = new NonPrefixedInstructionGroup(new Dictionary<byte, Instruction>
            {
                { 0x00, new Instruction(NOP, new List<int> { 4 }) },
                { 0x01, new Instruction(LoadDDNN, new List<int> { 4, 3, 3 }) },
                { 0x02, new Instruction(LoadBCA, new List<int> { 4, 3 }) },
                { 0x04, new Instruction(IncrementR, new List<int> { 4 }) },
                { 0x06, new Instruction(LoadRN, new List<int> { 4, 3 }) },
                { 0x07, new Instruction(RotateLeftCarryA, new List<int> { 4 }) },
                { 0x0A, new Instruction(LoadABC, new List<int> { 4, 3 }) },
                { 0x0C, new Instruction(IncrementR, new List<int> { 4 }) },
                { 0x0E, new Instruction(LoadRN, new List<int> { 4, 3 }) },
                { 0x11, new Instruction(LoadDDNN, new List<int> { 4, 3, 3 }) },
                { 0x12, new Instruction(LoadDEA, new List<int> { 4, 3 }) },
                { 0x14, new Instruction(IncrementR, new List<int> { 4 }) },
                { 0x16, new Instruction(LoadRN, new List<int> { 4, 3 }) },
                { 0x17, new Instruction(RotateLeftA, new List<int> { 4 }) },
                { 0x1A, new Instruction(LoadADE, new List<int> { 4, 3 }) },
                { 0x1C, new Instruction(IncrementR, new List<int> { 4 }) },
                { 0x1E, new Instruction(LoadRN, new List<int> { 4, 3 }) },
                { 0x21, new Instruction(LoadDDNN, new List<int> { 4, 3, 3 }) },
                { 0x24, new Instruction(IncrementR, new List<int> { 4 }) },
                { 0x26, new Instruction(LoadRN, new List<int> { 4, 3 }) },
                { 0x2C, new Instruction(IncrementR, new List<int> { 4 }) },
                { 0x2E, new Instruction(LoadRN, new List<int> { 4, 3 }) },
                { 0x31, new Instruction(LoadDDNN, new List<int> { 4, 3, 3 }) },
                { 0x32, new Instruction(LoadNNA, new List<int> { 4, 3, 3, 3 }) },
                { 0x36, new Instruction(LoadHLN, new List<int> { 4, 3, 3 }) },
                { 0x3A, new Instruction(LoadANN, new List<int> { 4, 3, 3, 3 }) },
                { 0x3C, new Instruction(IncrementR, new List<int> { 4 }) },
                { 0x3E, new Instruction(LoadRN, new List<int> { 4, 3 }) },

                { 0x40, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x41, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x42, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x43, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x44, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x45, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x46, new Instruction(LoadRHL, new List<int> { 4, 3 }) },
                { 0x47, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x48, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x49, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x4A, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x4B, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x4C, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x4D, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x4E, new Instruction(LoadRHL, new List<int> { 4, 3 }) },
                { 0x4F, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x50, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x51, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x52, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x53, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x54, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x55, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x56, new Instruction(LoadRHL, new List<int> { 4, 3 }) },
                { 0x57, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x58, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x59, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x5A, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x5B, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x5C, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x5D, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x5E, new Instruction(LoadRHL, new List<int> { 4, 3 }) },
                { 0x5F, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x60, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x61, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x62, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x63, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x64, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x65, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x66, new Instruction(LoadRHL, new List<int> { 4, 3}) },
                { 0x67, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x68, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x69, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x6A, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x6B, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x6C, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x6D, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x6E, new Instruction(LoadRHL, new List<int> { 4, 3 }) },
                { 0x6F, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x70, new Instruction(LoadHLR, new List<int> { 4, 3 }) },
                { 0x71, new Instruction(LoadHLR, new List<int> { 4, 3 }) },
                { 0x72, new Instruction(LoadHLR, new List<int> { 4, 3 }) },
                { 0x73, new Instruction(LoadHLR, new List<int> { 4, 3 }) },
                { 0x74, new Instruction(LoadHLR, new List<int> { 4, 3 }) },
                { 0x75, new Instruction(LoadHLR, new List<int> { 4, 3 }) },
                { 0x77, new Instruction(LoadHLR, new List<int> { 4, 3 }) },
                { 0x78, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x79, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x7A, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x7B, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x7C, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x7D, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x7E, new Instruction(LoadRHL, new List<int> { 4, 3 }) },
                { 0x7F, new Instruction(LoadRR, new List<int> { 4 }) },
                { 0x80, new Instruction(AddAR, new List<int> { 4 }) },
                { 0x81, new Instruction(AddAR, new List<int> { 4 }) },
                { 0x82, new Instruction(AddAR, new List<int> { 4 }) },
                { 0x83, new Instruction(AddAR, new List<int> { 4 }) },
                { 0x84, new Instruction(AddAR, new List<int> { 4 }) },
                { 0x85, new Instruction(AddAR, new List<int> { 4 }) },
                { 0x87, new Instruction(AddAR, new List<int> { 4 }) },

                { 0xC2, new Instruction(JumpCCNN, new List<int> { 4, 3, 3 }) },
                { 0xC3, new Instruction(JumpNN, new List<int> { 4, 3, 3 }) },
                { 0xCA, new Instruction(JumpCCNN, new List<int> { 4, 3, 3 }) },
                { 0xD2, new Instruction(JumpCCNN, new List<int> { 4, 3, 3 }) },
                { 0xDA, new Instruction(JumpCCNN, new List<int> { 4, 3, 3 }) },
                { 0xE2, new Instruction(JumpCCNN, new List<int> { 4, 3, 3 }) },
                { 0xEA, new Instruction(JumpCCNN, new List<int> { 4, 3, 3 }) },
                { 0xF2, new Instruction(JumpCCNN, new List<int> { 4, 3, 3 }) },
                { 0xFA, new Instruction(JumpCCNN, new List<int> { 4, 3, 3 }) }
            });
        }

        public uint Step()
        {
            var opCode = _memory.ReadByte(Registers.ProgramCounter++);

            var prefixedInstructionGroup = _prefixedInstructionGroups.FirstOrDefault(x => x.Prefix == opCode);
            return prefixedInstructionGroup?.Execute(_memory.ReadByte(Registers.ProgramCounter++))
                   ?? _nonPrefixedInstructionGroup.Execute(opCode);
        }

        private void NOP(byte opCode)
        { }
    }
}
